org: mhoward91
app: flaskapi
service: flaskapi

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: eu-west-2
  memorySize: 128
  profile: apiprofile
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["FootballersDynamoDBTable", "Arn"] }
  environment:
    FOOTBALLERS_TABLE: ${self:custom.tableName}
    
plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
  tableName: 'footballers-table-${self:provider.stage}'
  wsgi:
    app: api_dynamo.app
    packRequirements: false
functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

resources:
  Resources:
    FootballersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: player
            AttributeType: S
        KeySchema:
          -
            AttributeName: player
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}